name = "micro-cap-trader"
main = "src/index.jsx"
compatibility_date = "2024-09-17"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "trading-platform"
database_id = "placeholder-for-local-dev"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Custom domain (optional)
# routes = [
#   { pattern = "trader.example.com/*", zone_name = "example.com" }
# ]